Categories:
  - Utilities
  - Productivity
License: MIT
SourceCode: https://gitlab.com/ferreiratechlab/reaSalva

RepoType: git
Repo: https://gitlab.com/ferreiratechlab/reaSalva

Builds:
  - versionName: '1.0'
    versionCode: 1
    commit: main
    subdir: app
    gradle:
      - yes

AutoUpdateMode: None
UpdateCheckMode: None
CurrentVersion: '1.0'
CurrentVersionCode: 1

